<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("mid_lawyer/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("mid_lawyer/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Guid</th>
            <th>BasicInfo</th>
            <th>BasicInfo Of En</th>
            <th>Info</th>
            <th>Info Of En</th>
            <th>Flag</th>
            <th>Sign</th>
            <th>Sign Of En</th>
            <th>Updatetime</th>
            <th>Updated</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $mid_lawyer): ?>
            <tr>
                <td><?php echo $mid_lawyer->id ?></td>
            <td><?php echo $mid_lawyer->guid ?></td>
            <td><?php echo $mid_lawyer->basicInfo ?></td>
            <td><?php echo $mid_lawyer->basicInfo_en ?></td>
            <td><?php echo $mid_lawyer->info ?></td>
            <td><?php echo $mid_lawyer->info_en ?></td>
            <td><?php echo $mid_lawyer->flag ?></td>
            <td><?php echo $mid_lawyer->sign ?></td>
            <td><?php echo $mid_lawyer->sign_en ?></td>
            <td><?php echo $mid_lawyer->updatetime ?></td>
            <td><?php echo $mid_lawyer->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("mid_lawyer/edit/" . $mid_lawyer->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("mid_lawyer/delete/" . $mid_lawyer->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("mid_lawyer/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("mid_lawyer/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("mid_lawyer/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("mid_lawyer/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
